### ISSUE TITLE
[BUG] Migration error on FreeBSD 12.0 install

### ISSUE THREAD

**Issue by HugoSoszynski** [VultureProject/vulture-gui#13]
**Describe the bug**
Installed Vulture 4 to a bare metal FreeBSD 12.0 following:
- https://github.com/VultureProject/vulture-base/blob/master/BUILDING.md
- https://github.com/VultureProject/vulture-base/blob/master/CONFIGURE.md

When configuring hostname for the first time I got a migration error in `/usr/home/jails.apache/.zfs-source/home/vlt-os/vulture_os/darwin/migrations/0006_auto_20190829_1041.py` around line 14-15 because `m.db` does not exist.

**Plateform (please complete the following information):**
 - OS (version): FreeBSD 12.0
 - Vulture BASE version: 0.9.7
 - Vulture GUI version: 0.9.92

**To Reproduce**
Try installing a new bare metal Vulture 4 instance from the pages mentioned above.

**Expected behavior**
Bootstrap ending without error.

**Additional context**
Workaround:
```python
    if m.db and m.db['vulture']:
        coll = m.db['vulture']['darwin_filterpolicy']
        if coll:
            coll.delete_many({})
        coll = m.db['vulture']['darwin_darwinfilter']
        if coll:
            coll.delete_many({})

```

**Comment by KGuillemot** [comment]
Fixed on release 0.9.93
