### ISSUE TITLE
[BUG] Missing threshold in generated darwin.conf

### ISSUE THREAD

**Issue by HugoSoszynski** [VultureProject/vulture-gui#14]
**Describe the bug**
In the generated darwin configuration file, the field `threshold` is missing.
This prevent filters from raising alert.

**Plateform (please complete the following information):**
 - OS (version): 12.0
 - Vulture BASE version: 0.9.7
 - Vulture GUI version: 0.9.92

**To Reproduce**
```bash
cat /home/darwin/conf/darwin.conf
```

**Additional context**

Solution:

/home/vlt-os/vulture_os/services/config/darwin.conf
```json
    "{{filterpolicy.name}}": { 
        "exec_path": "{{filterpolicy.filter.exec_path}}", 
        "config_file": "{{filterpolicy.conf_path}}", 
        "nb_thread": "{{filterpolicy.nb_thread}}", 
        "log_level": "{{filterpolicy.log_level}}", 
        "cache_size": "{{filterpolicy.cache_size}}", 
        "output": "LOG", 
        "next_filter": "{{logs_filter.name}}_1", 
        "threshold": "{{filterpolicy.threshold}}" 
    } 
```

**Comment by KGuillemot** [comment]
Fixed on release 0.9.93
