### ISSUE TITLE
[BUG] PF block rules are logging

### ISSUE THREAD

**Issue by HugoSoszynski** [VultureProject/vulture-gui#26]
**Describe the bug**
The default block rules in /usr/local/etc/pf.conf are logging.

**Plateform:**
 - OS (version): FreeBSD 12.0
 - Vulture Base: 0.9.91
 - Vulture GUI: 0.9.95

**Expected behavior**
Not logging the dropped packets.

**Screenshots/logs**
Here is the code involved:
https://github.com/VultureProject/vulture-gui/blob/master/vulture_os/services/config/pf.conf#L177

**Comment by jjourdin** [comment]
Fixed in dev branch, thanks for reporting.
