### ISSUE TITLE
require updated djongo package

### ISSUE THREAD

**Issue by akashtalole** [VultureProject/vulture-gui#267]
I am using https://github.com/VultureProject/djongo for build and getting below error
AttributeError: module 'djongo.models' has no attribute 'JSONField'
AttributeError: module 'djongo.models' has no attribute 'ArrayField'
AttributeError: module 'djongo.models' has no attribute 'UniqueConstraint'

TypeError: __init__() got an unexpected keyword argument 'model_container'

**Comment by ELDiablO59152** [comment]
Djongo has been upgraded to suit Django 4 and may resolve your issue
