### ISSUE TITLE
Cannot assign HTTP listener to HTTP workflow

### ISSUE THREAD

**Issue by frikilax** [VultureProject/vulture-gui#36]
# Description
With at least one HTTP listener and HTTP application correctly created, it is impossible to create a complete workflow from them.

# Details
When trying to add the HTTP listener, a popup appears to define related FQDN and Public dir, however the popup is empty and thus  the listener cannot be added 

# Screenshots
![image](https://user-images.githubusercontent.com/33118448/73338762-982f4e80-4277-11ea-96ba-1c11f157cf4a.png)

**Comment by Raznak** [comment]
Fixed
