### ISSUE TITLE
[IDEA] HAProxy: Adding UNIX socket backend and Darwin listeners

### ISSUE THREAD

**Issue by HugoSoszynski** [VultureProject/vulture-gui#9]
**What is your feature about ?**
- Adding the possibility to create UNIX socket backend
- Adding the possibility to create a listener that redirects to a darwin filter UNIX socket
- Adding the possibility to create a listener that redirects to the darwin manager management UNIX socket

**Describe what you'd like**
I would like to easily setup listeners to access darwin filters and management API via a TCP connection.

The goal is to be able to call darwin filters synchronously or not from a distant service and to get information about the filter's runtime status (via the manager's socket).

**Comment by ELDiablO59152** [comment]
Feature added in the release 1.2.8
